stages:
    - build
before_script:
  - 'C:\Nuget\nuget.exe restore ".\TestCiApp\TestCiApp.sln"'
job:
    stage: build
    script: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe" ".\TestCiApp\TestCiApp.sln"'