// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NsSqliteServer.Data;

namespace NsSqliteServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181203191229_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("NsSqliteServer.Models.Lichtpunkt", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("hex(randomblob(16))");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Ort");

                    b.Property<string>("Straße");

                    b.HasKey("Id");

                    b.ToTable("Lichtpunkt");
                });
#pragma warning restore 612, 618
        }
    }
}
